### ISSUE TITLE
vert.x exception while shutting down

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-hazelcast#38] opened 2016-05-25 14:02 UTC
_From @tobiloeb on May 24, 2016 14:0_
### Version
- vert.x core: 3.2.1
- vert.x web: 3.2.1
- vert.x hazelcast: 3.2.1
### Context

Hello,

we have started vert.x  in cluster mode with two nodes. Everything is working fine until we shutdown the server. The server can't shutdown correctly and it fails with attached exception.
Both servers shut down at same time via jvm term signal. 

Seems to be related with Hazelcast.

> 2016-05-24 15:50:43,034 INFO  hz._hzInstance_1_dev.IO.thread-in-1 com.hazelcast.nio.tcp.TcpIpConnection - [server1]:38232 [dev] [3.5.2] Connection [Address[server2]:38232] lost. Reason: java.io.EOFException[Remote socket closed!]
> 2016-05-24 15:50:43,034 INFO  hz._hzInstance_1_dev.IO.thread-in-0 com.hazelcast.nio.tcp.TcpIpConnection - [server1]:38232 [dev] [3.5.2] Connection [Address[server2]:38232] lost. Reason: java.io.EOFException[Remote socket closed!]
> 2016-05-24 15:50:43,107 WARN  hz._hzInstance_1_dev.IO.thread-in-0 com.hazelcast.nio.tcp.ReadHandler - [server1]:38232 [dev] [3.5.2] hz._hzInstance_1_dev.IO.thread-in-0 Closing socket to endpoint Address[server2]:38232, Cause:java.io.EOFException: Remote socket closed!
> 2016-05-24 15:50:43,107 WARN  hz._hzInstance_1_dev.IO.thread-in-1 com.hazelcast.nio.tcp.ReadHandler - [server1]:38232 [dev] [3.5.2] hz._hzInstance_1_dev.IO.thread-in-1 Closing socket to endpoint Address[server2]:38232, Cause:java.io.EOFException: Remote socket closed!
> 2016-05-24 15:50:43,157 INFO  hz.ShutdownThread com.hazelcast.core.LifecycleService - [server1]:38232 [dev] [3.5.2] Address[server1]:38232 is SHUTTING_DOWN
> 2016-05-24 15:50:43,157 WARN  hz.ShutdownThread com.hazelcast.instance.Node - [server1]:38232 [dev] [3.5.2] Terminating forcefully...
> 2016-05-24 15:50:43,158 INFO  hz.ShutdownThread com.hazelcast.instance.Node - [server1]:38232 [dev] [3.5.2] Shutting down connection manager...
> 2016-05-24 15:50:43,164 INFO  hz.ShutdownThread com.hazelcast.instance.Node - [server1]:38232 [dev] [3.5.2] Shutting down node engine...
> 2016-05-24 15:50:43,175 INFO  hz.ShutdownThread com.hazelcast.instance.NodeExtension - [server1]:38232 [dev] [3.5.2] Destroying node NodeExtension.
> 2016-05-24 15:50:43,176 INFO  hz.ShutdownThread com.hazelcast.instance.Node - [server1]:38232 [dev] [3.5.2] Hazelcast Shutdown is completed in 19 ms.
> 2016-05-24 15:50:43,214 ERROR vert.x-eventloop-thread-17 i.v.c.e.impl.clustered.ClusteredEventBus - Failed to remove sub
> com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
>                 at com.hazelcast.spi.AbstractDistributedObject.throwNotActiveException(AbstractDistributedObject.java:81)
>                 at com.hazelcast.spi.AbstractDistributedObject.lifecycleCheck(AbstractDistributedObject.java:76)
>                 at com.hazelcast.spi.AbstractDistributedObject.getNodeEngine(AbstractDistributedObject.java:70)
>                 at com.hazelcast.multimap.impl.ObjectMultiMapProxy.remove(ObjectMultiMapProxy.java:125)
>                 at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMultiMap.lambda$remove$31(HazelcastAsyncMultiMap.java:123)
>                 at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$17(ContextImpl.java:296)
>                 at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$265(OrderedExecutorFactory.java:91)
>                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>                 at java.lang.Thread.run(Thread.java:745)
> 2016-05-24 15:50:43,222 ERROR vert.x-eventloop-thread-10 io.vertx.core.impl.DeploymentManager - Failure in calling handler
> com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
>                 at com.hazelcast.spi.AbstractDistributedObject.getService(AbstractDistributedObject.java:93)
>                 at com.hazelcast.map.impl.proxy.MapProxySupport.toData(MapProxySupport.java:1143)
>                 at com.hazelcast.map.impl.proxy.MapProxyImpl.remove(MapProxyImpl.java:178)
>                 at io.vertx.core.impl.HAManager.stop(HAManager.java:195)
>                 at io.vertx.core.impl.VertxImpl.lambda$close$278(VertxImpl.java:461)
>                 at io.vertx.core.impl.DeploymentManager.lambda$undeployAll$158(DeploymentManager.java:238)
>                 at io.vertx.core.impl.DeploymentManager.lambda$reportResult$161(DeploymentManager.java:398)
>                 at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335)
>                 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
>                 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
>                 at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
>                 at java.lang.Thread.run(Thread.java:745)
> 2016-05-24 15:50:43,261 INFO  hz.ShutdownThread com.hazelcast.core.LifecycleService - [server1]:38232 [dev] [3.5.2] Address[server1]:38232 is SHUTDOWN

Thanks in advanced for any help
Tobias

_Copied from original issue: vert-x3/vertx-web#384_

**Comment by pmlopes** [comment] 2016-05-25 14:03
_From @purplefox on May 25, 2016 7:23_

Does the issue occur if you stagger the shutdown?

**Comment by pmlopes** [comment] 2016-05-25 14:03
_From @jtrumpfheller on May 25, 2016 11:46_

This is something we can't check. We have to use the server as they are and adjustments are definitely not possible.

**Comment by pmlopes** [comment] 2016-05-25 14:03
_From @purplefox on May 25, 2016 12:1_

Can't you try in your development or staging environment?

**Comment by pmlopes** [comment] 2016-05-25 14:03
_From @jtrumpfheller on May 25, 2016 12:4_

Sadly no. And we only have windows computer for development so we even can't reproduce it locally.

**Comment by cescoffier** [comment] 2016-05-26 13:49
The issue lies in the HAManager that accesses a distributed object after the Hazelcast instance been closed.

**Comment by cescoffier** [comment] 2016-05-30 06:37
A PR on Core has been opened.

**Comment by jtrumpfheller** [comment] 2016-05-30 15:18
Thanks for your investigation and the fix.Will it be included in 3.3.0 release?

Have you already pushed the fix? Cause I can't see it yet: https://github.com/eclipse/vert.x/pulls?q=

**Comment by cescoffier** [comment] 2016-05-30 15:20
No it's awaiting the review and integration by @vietj

**Comment by vietj** [comment] 2016-05-30 15:26
where is the PR ?

**Comment by cescoffier** [comment] 2016-05-30 15:40
IT's the commit I asked you to review last week:
https://github.com/cescoffier/vert.x/commit/6f8c55741ae8cbb703e5f73069c30b577ec96e63

**Comment by jtrumpfheller** [comment] 2016-06-14 07:23
Any updates so far?

**Comment by jclosure** [comment] 2016-08-23 05:13
When running ClusteredVertx and Hazelcast in a Spring container, this issue presents when the app exits, because order of bean teardown cannot be guaranteed.  In our case, Hazelcast is getting disposed out from under Vertx on applicationContext.close().  Would like to see this fix make it in, because it spuriously spams our logs with errors.

**Comment by cescoffier** [comment] 2016-08-23 06:24
Are you using your own Hazelcast instance ?

**Comment by jclosure** [comment] 2016-09-03 20:03
Yes.  We have create our HazelcastInstance.  Then we use it to create a HazelcastClusterManager.  When we create clustered Vertx instance with it.

The HazelcastInstance shown below is already created by us.  Here's how we have it set up.

```java
final VertxOptions vertxOptions = new VertxOptions();

final ClusterManager clusterManager = new HazelcastClusterManager(hazelcastInstance);
        vertxOptions.setClusterManager(clusterManager);

Vertx.clusteredVertx(vertxOptions, vres -> {
    // ...
});
```

**Comment by cescoffier** [comment] 2016-09-05 07:41
@jclosure are you using HA with Vert.x in a Spring app ?

**Comment by jclosure** [comment] 2016-09-05 15:59
@cescoffier Yes.  Spring manages a Vertx instance and and a Hazelcast instance for each node in our cluster.

**Comment by ngmip** [comment] 2017-01-10 15:22
I have a similar problem when Spring manages the Hazecastlnstance. 

As it's managed by Spring, when the application context is closed, Spring automatically calls the "shutdown" method on the Hazecastlnstance. 
Later when Vertx is closed (also managed by spring in my case) the Hazecastlnstance is closed again and the "Hazelcast instance is not active!" error stack arises.

If you manage the way the Hazecastlnstance is created through an `@Bean` method, you may configure the "destroyMethod" ( `@Bean(destroyMethod="")` ) so that spring won't take care of the "shutdown" and leaves it to you (or Vertx).

As I did not want spring to manage the Hazecastlnstance at all I excluded the HazelcastAutoConfiguration class from the SpringBootApplication (which in my case was responsible for putting the instance created by Vertx in the application context).

One dummy thought can be: could Vertx check whether the instance was closed before attempting to close it ?
But the solution might not be that simple...

**Comment by tsegismont** [comment] 2017-01-10 15:50
@ngmip when the HazelcastClusterManager is created manually provided an externally managed HazelcastInstance, Vert.x does not try to stop Hazelcast. It's the user's responsibility to ensure the HazelcastInstance is not closed before Vert.x is.

I would expect Spring to not shutdown Hazelcast if it's injected in another bean. which is not destroyed yet. If doesn't then it's a Spring dependency management issue.

**Comment by tsegismont** [comment] 2017-01-11 09:29
Also, if Hazelcast is managed by the user, it's important that the property `hazelcast.shutdownhook.enabled` is set to false. This can be a Java system property or an element of the `properties` section in Hazelcast XML config:

```xml
<property name="hazelcast.shutdownhook.enabled">false</property>
```

Vert.x does this for you when it manages Hazelcast.

Please reopen if you have simple reproducer.

**Closed by tsegismont** 2017-01-11 09:29 UTC
