### ISSUE TITLE
Problem while reading DataSerializable

### ISSUE THREAD

**Issue by alexander-burykin** [vert-x3/vertx-hazelcast#67] opened 2017-03-16 07:55 UTC
2017-03-16_05:42:43.32981 com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: 0, id: 0, class: 'io.vertx.spi.cluster.hazelcast.impl.Hazelcas
tAsyncMap$DataSerializableHolder', exception: Failed to load class io.vertx.ext.web.sstore.impl.SessionImpl
2017-03-16_05:42:43.32982       at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:130)
2017-03-16_05:42:43.32983       at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47)
2017-03-16_05:42:43.32983       at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
2017-03-16_05:42:43.32984       at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:170)
2017-03-16_05:42:43.32985       at com.hazelcast.map.impl.proxy.MapProxySupport.toObject(MapProxySupport.java:940)
2017-03-16_05:42:43.32985       at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:94)
2017-03-16_05:42:43.32985       at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMap.lambda$get$0(HazelcastAsyncMap.java:46)
2017-03-16_05:42:43.32986       at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:263)
2017-03-16_05:42:43.32988       at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$0(OrderedExecutorFactory.java:94)
2017-03-16_05:42:43.32989       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2017-03-16_05:42:43.32989       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2017-03-16_05:42:43.32989       at java.lang.Thread.run(Thread.java:745)
2017-03-16_05:42:43.32990 Caused by: java.lang.IllegalStateException: Failed to load class io.vertx.ext.web.sstore.impl.SessionImpl
2017-03-16_05:42:43.32990       at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMap$DataSerializableHolder.readData(HazelcastAsyncMap.java:178)
2017-03-16_05:42:43.32991       at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:121)
2017-03-16_05:42:43.32991       ... 11 more
2017-03-16_05:42:43.32992 Caused by: java.lang.InstantiationException: io.vertx.ext.web.sstore.impl.SessionImpl
2017-03-16_05:42:43.32992       at java.lang.Class.newInstance(Class.java:427)
2017-03-16_05:42:43.32992       at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMap$DataSerializableHolder.readData(HazelcastAsyncMap.java:175)
2017-03-16_05:42:43.32995       ... 12 more
2017-03-16_05:42:43.32995 Caused by: java.lang.NoSuchMethodException: io.vertx.ext.web.sstore.impl.SessionImpl.<init>()
2017-03-16_05:42:43.32997       at java.lang.Class.getConstructor0(Class.java:3082)
2017-03-16_05:42:43.32997       at java.lang.Class.newInstance(Class.java:412)
2017-03-16_05:42:43.32998       ... 13 more

**Comment by tsegismont** [comment] 2017-03-16 09:12
Duplicate of vert-x3/vertx-web#549

Will be fixed in 3.4.1

**Closed by tsegismont** 2017-03-16 09:12 UTC
